## 张量基本操作

pytorch中操作的基本元素是张量，其实和numpy的ndarrays是一样的，区别在于张量可以用于GPU运算

In [1]:
import torch
# 构造一个5x3的零张量
x = torch.empty(5,3)
print(x)

tensor([[1.7753e+28, 7.0744e+31, 1.1358e+30],
        [1.7743e+28, 2.0535e-19, 2.7909e+23],
        [3.8946e+21, 4.4650e+30, 4.6172e+24],
        [1.4353e-19, 2.7530e+12, 7.5338e+28],
        [1.5975e-43, 0.0000e+00, 0.0000e+00]])


In [7]:
# 构造一个随机生成的5x3张量
x = torch.rand(5,3)
print(x)

tensor([[0.2188, 0.7866, 0.4125],
        [0.2884, 0.1567, 0.1277],
        [0.6822, 0.9331, 0.5572],
        [0.8185, 0.3433, 0.1488],
        [0.9651, 0.0595, 0.9173]])


In [8]:
# 张量在构造的时候还可以指定类型
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
# 从list中构造张量
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [15]:
# 也可以从现有的张量中构造新的张量
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

# 构造一个大小和x相同，但是用新的随机数填充的张量
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2924,  0.5526,  0.3168],
        [ 0.5561, -1.8109, -0.5931],
        [ 1.1207,  0.7190,  0.3638],
        [-1.1611, -1.0806,  1.4478],
        [-1.5854, -0.9577,  0.7642]])


In [16]:
# 得到张量大小
print(x.size())

torch.Size([5, 3])


## 张量基本运算

In [17]:
# 相加
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.6780,  1.4184,  0.4915],
        [ 1.2844, -0.8814, -0.3373],
        [ 1.9303,  1.3879,  0.3662],
        [-1.0566, -0.2586,  1.9340],
        [-1.5152, -0.6675,  0.8946]])


In [18]:
# 相加
print(torch.add(x, y))

tensor([[ 0.6780,  1.4184,  0.4915],
        [ 1.2844, -0.8814, -0.3373],
        [ 1.9303,  1.3879,  0.3662],
        [-1.0566, -0.2586,  1.9340],
        [-1.5152, -0.6675,  0.8946]])


In [21]:
# 将相加结果保存到指定变量中
result = torch.empty(1, 1)
torch.add(x, y, out=result) # 如果result大小和计算结果大小不同，pytorch会自动转换
print(result)

tensor([[ 0.6780,  1.4184,  0.4915],
        [ 1.2844, -0.8814, -0.3373],
        [ 1.9303,  1.3879,  0.3662],
        [-1.0566, -0.2586,  1.9340],
        [-1.5152, -0.6675,  0.8946]])


In [22]:
# 将x加到y上
y.add_(x)
print(y)

tensor([[ 0.6780,  1.4184,  0.4915],
        [ 1.2844, -0.8814, -0.3373],
        [ 1.9303,  1.3879,  0.3662],
        [-1.0566, -0.2586,  1.9340],
        [-1.5152, -0.6675,  0.8946]])


> Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

## 张量索引

张量索引方法和numpy基本一样

In [24]:
# 取第2列
print(x[:,1])

tensor([ 0.5526, -1.8109,  0.7190, -1.0806, -0.9577])


In [27]:
# 也可以更改张量大小，但是不是numpy.reshape，而是view
x = torch.randn(4, 4)
y = x.view(16)  # 是深度拷贝
z = x.view(-1, 8) # 可以指定某个axis为-1， 让pytorch自己计算
print(x.size(),y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [2]:
# 如果你的张量只有一个元素，可以直接使用item方法取得
x = torch.randn(1)
print(x, x.item(), type(x.item()))

tensor([-0.5526]) -0.5525521636009216 <class 'float'>


In [34]:
# 对于张量，可以直接调用numpy方法获得numpy的ndarrays类型
a = torch.ones(5)
print(a)
b = a.numpy()  # 注意，这里返回的是数据的视图，而不是拷贝！
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [35]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [36]:
# 将numpy类型转为torch
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) # 注意这里同样是返回的视图，而不是拷贝！
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


> All the Tensors on the **CPU** except a CharTensor support converting to NumPy and back.

## 使用GPU加速

张量可以调用to方法将张量转移到任何支持的设备上

In [3]:
if torch.cuda.is_available():  # 检测cuda是否安装
    device = torch.device('cuda')  # 转移到cuda上
    y = torch.ones_like(x, device = device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))  # 使用CPU运算

tensor([0.4474], device='cuda:0')
tensor([0.4474], dtype=torch.float64)
