#### ReLU函数
$$
ReLU(x)=max(0,x)
$$

In [4]:
import torch
from torch import nn
relu = nn.ReLU(inplace=True)

In [8]:
input = torch.randn(2,3)
print(input)
output = relu(input)  # apply relu
print(output)
print(input == output) # 直接覆盖input

tensor([[-1.4688,  1.1435,  0.3796],
        [-0.3736,  0.0114, -0.1835]])
tensor([[0.0000, 1.1435, 0.3796],
        [0.0000, 0.0114, 0.0000]])
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)
